version: '3.8'

services:
    app:
      build:
        context: ..
        dockerfile: ./docker/nvim/Dockerfile
      volumes:
        - ../nvim:/home/username/.config/nvim
        - ./nvim/.local:/home/username/.local
